$schema: "http://json-schema.org/draft-06/schema#"

description: seq2science gene expression configuration

properties:
  # paths to store results
  fastq_clean_dir:
    description: directory where to find the workflow rules
    default: fastq_cleaned
    type: string
  # fastq-pair
  fastq-pair:
      description: fastq synchronization
      default: '-p'
  # quantifier
  quantifier:
    description: which quantifier to use
    properties:
      kallistobus:
        properties:
          ref:
            default: ''
          count:
            default: ''
    default:
      kallistobus:
        ref: ''
        count: ''

  barcodefile:
    type: string

  
