$schema: "http://json-schema.org/draft-06/schema#"

description: seq2science gene expression configuration

properties:
  # paths to store results
  fastq_clean_dir:
    description: directory where to find the workflow rules
    default: fastq_cleaned
    type: string
  # fastq-pair
  fastq-pair:
      description: fastq synchronization
      default: '-t 1200003 -p'
  # quantifier
  quantifier:
    description: which quantifier to use
    properties:
      kallistobus:
        properties:
          ref:
            default: '--lamanno'
          count:
            default: '-x 0,8,16:0,0,8:1,0,0 --verbose --lamanno'
    default:
      kallistobus:
        ref: '--lamanno'
        count: '-x 0,8,16:0,0,8:1,0,0 --verbose --lamanno'

  barcodefile:
    type: string

  
